### ISSUE TITLE
[MDEP-951] Upgrade to Parent 43

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#1457]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MDEP-951](https://issues.apache.org/jira/browse/MDEP-951?redirect=false)** and commented

---
No further details from [MDEP-951](https://issues.apache.org/jira/browse/MDEP-951?redirect=false)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [5288cece722923651fbcf5e13741d3f94e910dbf](https://gitbox.apache.org/repos/asf?p=maven-dependency-plugin.git;a=commit;h=5288cece722923651fbcf5e13741d3f94e910dbf).

**Comment by slawekjaranowski** [comment]
- #424
